<?xml version="1.0" encoding="utf-8"?><Database Name="Express" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Express;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ExpressConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Branch" Member="Branch">
    <Type Name="Branch">
      <Column Name="bId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="province" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="city" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="street" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Branch_Package" Member="Package" ThisKey="bId" OtherKey="srcId" Type="Package" />
      <Association Name="Branch_Package1" Member="Package1" ThisKey="bId" OtherKey="destId" Type="Package" />
    </Type>
  </Table>
  <Table Name="dbo.Login" Member="Login">
    <Type Name="Login">
      <Column Name="account" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="role" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Member" Member="Member">
    <Type Name="Member">
      <Column Name="mId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="job" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Member_Delivery" Member="Delivery" ThisKey="mId" OtherKey="mId" Type="Delivery" />
      <Association Name="Member_PickUp" Member="PickUp" ThisKey="mId" OtherKey="mId" Type="PickUp" />
      <Association Name="Member_Transfer" Member="Transfer" ThisKey="mId" OtherKey="mId" Type="Transfer" />
    </Type>
  </Table>
  <Table Name="dbo.Vehicle" Member="Vehicle">
    <Type Name="Vehicle">
      <Column Name="vId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Vehicle_Package" Member="Package" ThisKey="vId" OtherKey="vId" Type="Package" />
    </Type>
  </Table>
  <Table Name="dbo.Delivery" Member="Delivery">
    <Type Name="Delivery">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="mId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Member_Delivery" Member="Member" ThisKey="mId" OtherKey="mId" Type="Member" IsForeignKey="true" />
      <Association Name="Package_Delivery" Member="Package" ThisKey="id" OtherKey="id" Type="Package" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Error" Member="Error">
    <Type Name="Error">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="introduction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Package_Error" Member="Package" ThisKey="id" OtherKey="id" Type="Package" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PickUp" Member="PickUp">
    <Type Name="PickUp">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="mId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Member_PickUp" Member="Member" ThisKey="mId" OtherKey="mId" Type="Member" IsForeignKey="true" />
      <Association Name="Package_PickUp" Member="Package" ThisKey="id" OtherKey="id" Type="Package" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Transfer" Member="Transfer">
    <Type Name="Transfer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="mId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="srcId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="destId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Member_Transfer" Member="Member" ThisKey="mId" OtherKey="mId" Type="Member" IsForeignKey="true" />
      <Association Name="Package_Transfer" Member="Package" ThisKey="id" OtherKey="id" Type="Package" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Package" Member="Package">
    <Type Name="Package">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="weight" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="sendId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="receiverId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="srcId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="destId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Package_Delivery" Member="Delivery" ThisKey="id" OtherKey="id" Type="Delivery" />
      <Association Name="Package_Error" Member="Error" ThisKey="id" OtherKey="id" Type="Error" Cardinality="One" />
      <Association Name="Package_PickUp" Member="PickUp" ThisKey="id" OtherKey="id" Type="PickUp" />
      <Association Name="Package_Transfer" Member="Transfer" ThisKey="id" OtherKey="id" Type="Transfer" />
      <Association Name="Branch_Package" Member="Branch" ThisKey="srcId" OtherKey="bId" Type="Branch" IsForeignKey="true" />
      <Association Name="Branch_Package1" Member="Branch1" ThisKey="destId" OtherKey="bId" Type="Branch" IsForeignKey="true" />
      <Association Name="Vehicle_Package" Member="Vehicle" ThisKey="vId" OtherKey="vId" Type="Vehicle" IsForeignKey="true" />
      <Association Name="Customer_Package" Member="Customer" ThisKey="sendId" OtherKey="cId" Type="Customer" IsForeignKey="true" />
      <Association Name="Customer_Package1" Member="Customer1" ThisKey="receiverId" OtherKey="cId" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customer">
    <Type Name="Customer">
      <Column Name="cId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="province" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="street" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Customer_Package" Member="Package" ThisKey="cId" OtherKey="sendId" Type="Package" />
      <Association Name="Customer_Package1" Member="Package1" ThisKey="cId" OtherKey="receiverId" Type="Package" />
    </Type>
  </Table>
</Database>